spring.application.name=demo

#spring.profiles.active=test


spring.datasource.url=jdbc:postgresql://localhost:5432/ps_tournament
spring.datasource.username=postgres
spring.datasource.password=123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true



springdoc.swagger-ui.enabled=true
springdoc.api-docs.enabled=true


spring.mvc.format.date-time=yyyy-MM-dd HH:mm:ss
spring.jackson.date-format=yyyy-MM-dd HH:mm:ss
spring.jackson.time-zone=Asia/Baku



app.setup.admin.email=${admin-email}
app.setup.admin.password=${admin-password}
app.setup.admin.full-name=${admin-full-name}

SECRET_KEY=${SECRET_KEY}